
import "./globals.css";

export const metadata = {
  title: "Vinson Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className="bg-[#0f0f0f]"
      >
        {children}
      </body>
    </html>
  );
}
