import Footer from "../conponents/footer/footer";
import Navbar from "../conponents/navbar/navbar";
import "./globals.css";
import { ThemeProvider } from "./providers";

export const metadata = {
  title: "Vinson Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
        
        <body
          className=""
        >
          <Navbar />
          {children}
           <Footer />
        </body>
       
      </ThemeProvider>
    </html>
  );
}
